Minor modifications
ringmesh/web pull request #6
Opened 2017-11-21 08:08 UTC by BotellaA

2017-11-21 08:33 UTC, panquez requested changes
Thank you for these corrections. There is only one problem about the description of the GeoModelMesh

2017-11-21 08:33 UTC, panquez commented on docs/features/geomodel.md
> + * The `RINGMesh::GeoModelMeshEdges` this particular database is useful to represent wells.
This is wrong since now we have GeoModelMeshEdges for line mesh elements and GeoModelMeshWells for well mesh elements

2017-11-21 08:55 UTC, francoisbonneau commented
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/xq7CcLL7/2-test)

2017-11-21 11:12 UTC, francoisbonneau submitted a review, later dismissed

2017-11-22 13:43 UTC, panquez submitted a review, later dismissed

2017-11-22 13:49 UTC, merged